# Generated by Django 5.0.4 on 2024-05-11 05:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rememberapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="remember",
            name="comment",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="remember",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=None, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="remember",
            name="title",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
