# Generated by Django 5.0.4 on 2024-05-11 05:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rememberapp",
            "0002_remember_comment_remember_location_remember_title",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="remember",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="remember",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="remember",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
