# Generated by Django 5.0.4 on 2024-05-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
