name: Place Remember

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.12 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run black
        run:
          black --config=placesremember/pyproject.toml --check .
      - name: Run flake8
        run: flake8 --config=placesremember/.flake8
      - name: Run isort
        run: isort --profile black --filter-files .
      - name: Run Mypy
        run: mypy --config-file=placesremember/pyproject.toml --package-root placesremember/ .